### ISSUE TITLE
Tag 2.0.0?

### ISSUE THREAD

**Issue by Nyholm** [geocoder-php/geocoder-extra#44]
What is left to do before tagging 2.0?
After the merge of #40 all tests will be green and we fully support Gecoder 3.0. 

I want to tag 2.0 of geocoder-extra to make sure we have a working release with geocoder 3.0. Then tag 3.0 of geocoder-extra when 4.0 of geocoder is released. 

@vicchi Do you have anything else you want to do before 2.0?

**Comment by vicchi** [comment]
@Nyholm I'd like to have one last pass through the open issues and see if we can clear them up

**Comment by willdurand** [comment]
> I want to tag 2.0 of geocoder-extra to make sure we have a working release with geocoder 3.0. Then tag 3.0 of geocoder-extra when 4.0 of geocoder is released.

:+1:

Let's wait for @vicchi last pass, and then let's finally tag a new version! Thanks for your great work ❤️

**Comment by vicchi** [comment]
There's 3 open PRs at the moment.

@Nyholm's PR #40 looks like it's passing all the tests and needs LGTM and/or +1's.

PR #34 looks like it needs some remedial work, plus it's failing on the unit tests, as it PR #33 

In an ideal world I'd like to get these PR's either merged and/or updated and then merged or, worst case scenario, closed. Especially for the 2 oldest PR's which have asked for remedial action and which haven't, to date, been replied to.

Issue #30 seems to have gone quiet and issue #28 can probably be looked at and resolved.

I do plan on tackling all of the above, but I'm unsure as to timescales on all of this due to the day job.

**Comment by Nyholm** [comment]
Good, thank you. 

I think we should do #34 and #28. I've updated the milestone: https://github.com/geocoder-php/geocoder-extra/milestone/1

@vicchi: Please review #40 and merge it if you like it.

**Comment by vicchi** [comment]
@Nyholm PR #40 is merged and closed. Nicely done

**Comment by Nyholm** [comment]
Thank you!

**Comment by Nyholm** [comment]
I've created #45 and #46. Please give those a review and I'll tag 2.0.0 later today.

**Comment by vicchi** [comment]
I'm also looking at PR #33 right now

**Comment by vicchi** [comment]
PR #33 needs work on the unit tests to pass; they've not been updated to reflect the new URLs that the Baidu provider now uses as a result of supporting v2 of their API. Which makes me think they haven't been run at all for this PR.

I'll go through them and a) try to fix them up to pass for the mocked tests and b) see if I can get hold of a live Baidu API key so we can test the live API calls.

Which will take longer than I anticipated, but such is life ....

**Comment by Nyholm** [comment]
That could be done after 2.0. Nothing will break BC, right?

**Comment by vicchi** [comment]
Right. Just reviewed #45 and #46. Both LGTM.

Let's punt the remaining issues and PRs 'till post 2.0 and then I'll make a concerted effort to clear up all the issues/PRs

**Comment by Nyholm** [comment]
Great. 

@willdurand are you okey with me tagging 2.0.0 now?

**Comment by willdurand** [comment]
Yes. Can you do it or I take care of it? (tomorrow)

**Comment by Nyholm** [comment]
Cool, Im happy to do it.

**Comment by willdurand** [comment]
awesome!!!
